# Выпуск №1: 7 стримов
[video]
title = "Лучшие моменты стримов"
minutes = 45

[[stream]]
url = "https://www.twitch.tv/videos/2890918336"

[[stream]]
url = "https://www.twitch.tv/videos/2895198615"

[[stream]]
url = "https://www.twitch.tv/videos/2895082498"

[[stream]]
url = "https://www.twitch.tv/videos/2878584690"

[[stream]]
url = "https://www.twitch.tv/videos/2887268104"

[[stream]]
url = "https://www.twitch.tv/videos/2895270510"

[[stream]]
url = "https://www.twitch.tv/videos/2895015095"
